version: "3"
services:
  dev_db:
    image: postgres
    ports:
      - 5432
    environment:
      - PG_PASSWORD=password
  dev_redis:
    image: redis
  gavel:
    container_name: gavel
    image: gavel:latest
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=5000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DEBUG=${DEBUG}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - FORCE_SSL=${FORCE_SSL}
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - dev_db
      - dev_redis
    volumes:
      - .:/gavel